networks:
    laravel:
        driver: bridge
services:
    mysql:
        container_name: mysql
        image: mysql/mysql-server:8.0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: pinycloud_db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        networks:
            - laravel
    app:
        container_name: app
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.app
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        tty: true
        depends_on:
            - mysql
        networks:
            - laravel
    nginx-server:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.server
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - laravel
    client:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile.node
        container_name: client
        volumes:
            - ./:/var/www/html
            - /var/www/node_modules
        working_dir: /var/www/html/
        ports:
            - "8080:8080"
        entrypoint:
            - sh
            - -c
            - |
                npm cache clean --force &&
                npm install &&
                npm run dev &&
                tail -f /dev/null
        depends_on:
            - app  # Ensure the Laravel app is running before starting the client
            - mysql  # Ensure the Laravel app is running before starting the client
        networks:
            - laravel
volumes:
    dbdata:
        driver: local
