// get list of category
export const GET_CATEGORIES_PROCESS = "GET_CATEGORIES_PROCESS";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const ADMIN_GET_CATEGORIES_PROCESS = "ADMIN_GET_CATEGORIES_PROCESS";

export const ADMIN_GET_CATEGORIES_SUCCESS = "ADMIN_GET_CATEGORIES_SUCCESS";

export const ADMIN_GET_CATEGORIES_FAIL = "ADMIN_GET_CATEGORIES_FAIL";
