FROM nginx:stable-alpine

# Copy the Nginx configuration file
ADD ./docker/nginx/conf.d/vhost.conf /etc/nginx/conf.d/default.conf
ADD vhost.conf /etc/nginx/conf.d/default.conf
COPY public /var/www/html/public

# Start Nginx
WORKDIR /var/www/html
CMD ["nginx", "-g", "daemon off;"]
